### ISSUE TITLE
Trident of the Seas not showing spell max hit

### ISSUE THREAD

**Issue by demonsdawn** [j-cob44/max-hit-calc#29]
Since the update my Trident does not display its correct max hit, it seems the built-in spell is not registered at all. Other powered staves might also be affected, but i am unable to verify. Auto-casting with normal staves works as intended. 

![2024-03-22 19_15_36-RuneLite - Demonsdawn](https://github.com/j-cob44/max-hit-calc/assets/24295180/dca40191-520d-45fe-a5be-942858bbc272)
Max hit at this level should be 24.
![2024-03-22 19_12_21-RuneLite - Demonsdawn](https://github.com/j-cob44/max-hit-calc/assets/24295180/8b5e6c30-a55f-4294-8079-3e9eb4a1a98e)
![2024-03-22 19_12_34-RuneLite - Demonsdawn](https://github.com/j-cob44/max-hit-calc/assets/24295180/ad0f38b4-7f7f-4333-8459-cf15710b703d)

**Comment by j-cob44** [comment]
Thanks for reporting this. Either the newest OSRS or Runelite update has broken this feature and I'm looking into fixing this ASAP.

**Comment by demonsdawn** [comment]
Figured I'd add this onto here, since it is likely related.
The Keris Partisan also seems to be acting a weird, it does not update its damage calculation and hovering over the UI element (while having it equipped) causes the window to disappear.
The Keris itself works fine.

**Comment by j-cob44** [comment]
@demonsdawn, the plugin has been updated in runelite and the powered staff issue has been fixed. Unfortunately, I was out of town over the weekend and was unable to work on the Partisan issue. Seems like there are a few more things broken from this OSRS update, please let me know if you find anymore.

**Comment by demonsdawn** [comment]
Will do!
I noticed the update to the powered staff, working perfectly, the quick fix is very appreciated.

**Comment by demonsdawn** [comment]
It appears the Longrange attack style on powered staves is still wrong.
![2024-03-29 23_43_01-Window](https://github.com/j-cob44/max-hit-calc/assets/24295180/494b77e4-5905-4481-9738-8f89bda72a58)

**Comment by j-cob44** [comment]
Hey, please let me know if you notice any other staves doing this, other than just powered staves.

**Comment by j-cob44** [comment]
Hey @demonsdawn, the fix for this was just accepted by Runelite and is now available as v1.12.5. Please restart your Runelite and the update should automatically be installed.

Please give it a try and let me know if you find anymore broken weapons! And thank you very much for reporting the issue!
